### PR TITLE
Fixed #398: added OOTB logic for all Google overlay types

### LINKED ISSUE #398: Add support for most/all drawing types in map theme

### PR DESCRIPTION
**Pull request by grtjn**

### CODE REVIEW

**Comment by grtjn** [comment]
Anyone who likes to take a spin with this?

**Comment by grtjn** [comment]
Dave points out that marker and polyline searches would make most sense with proximity searches. I'll open a new ticket to look into that, and drop those from the google drawing tools..

**Comment by daveegrant** [comment]
Everything else looks good to me.  I think it is ready to go.

**Comment by grtjn** [comment]
Thnx, I'll merge, ran sufficient tests with this..

**Pull request merged**
