### PR TITLE
Adds a favicon and adds it to index.html

### PR DESCRIPTION
**Pull request by hunterwilliams**
This would complete #56 

Not exactly sure what the icon is originally from but I had it from another ML project.

### CODE REVIEW

**Comment by joemfb** [comment]
Looks good!

One comment: according to https://stackoverflow.com/questions/10218178/necessary-to-add-link-tag-for-favicon-ico, `rel="shortcut icon"` is from an old version of IE; the new standard is just `rel="icon"`.

**Comment by hunterwilliams** [comment]
I'm game but wondering... How far back do we support?

**Comment by grtjn** [comment]
This site also mentions apple-touch-icon something: http://iconhandbook.co.uk/reference/examples/favicons/

I wouldn't mind that shortcut bit, its just 9 chars, and harming no one.. ;)

**Comment by hunterwilliams** [comment]
@grtjn I suggest we avoid the apple-touch-icon. It opens a can of worms and then you need a bunch of different sizes etc. If we were pushing a mobile based app sure but I don't think we're doing that.


@joemfb Would it be okay to just leave it in for legacy purposes?

**Comment by joemfb** [comment]
I'm not attached one way or another; just sharing what I had learned ;)

**Comment by hunterwilliams** [comment]
<link rel="shortcut icon" href="http://owwgdpc6ll4w6eh4717xd1x4.wpengine.netdna-cdn.com/wp-content/mu-plugins/images/favicon.ico?cache=2">

That's what marklogic.com does. I've changed the favicon to use that one. Squashed the commit down to one.

**Comment by grtjn** [comment]
Wow...

**Comment by grtjn** [comment]
Odd, not seeing the update you commented. Forgot to push maybe?

**Comment by hunterwilliams** [comment]
Sorry I squashed it down. Should have waited.  It's there though :)

**Comment by grtjn** [comment]
Squashing it should not hide it from the diff. I am really not seeing it, just:

```
<link rel="shortcut icon" href="/images/favicon.ico" />
```

and a binary we no longer need..

**Comment by hunterwilliams** [comment]
Sorry I meant I grabbed the binary from the cdn and used that. I don't think we should link to MarkLogic's cdn

**Comment by grtjn** [comment]
Ah cool, even better!

**Comment by grtjn** [comment]
Worked nicely for me, merging..

**Pull request merged**
