### PR TITLE
fixed issue #149 and #142.

### PR DESCRIPTION
**Pull request by jenbreese**
This is a fix for issue #149 and #142. Also removed the additional space on the login box and changed the order of the buttons. The cancel button should be on the left and the submit on the right, due to convention.

### CODE REVIEW

**Comment by grtjn** [comment]
@jenbreese Wanna leave this open for more UI fixes?

**Comment by jenbreese** [comment]
@grtjn, whichever is the team's preference. I have other css fixes for the day too.

**Comment by grtjn** [comment]
Don't think it matters much. I'll hold off for now, saves you opening a new PR for each commit..

**Comment by grtjn** [comment]
#171, #156

**Comment by grtjn** [comment]
Looking good!

**Pull request merged**
