### PR TITLE
Fixes #319 - Angular bootstrap directive changes

### LINKED ISSUE #319: Angular bootstrap directive changes
Angular bootstrap now prepends all their directive names with `uib-`. We should migrate too, and make sure all still works well.

Snippet selection seems to malfunction in latest slush, (or maybe just in UI templates)..

### PR DESCRIPTION
**Pull request by Audarth**
Refactored to now use ui bootstrap 0.14 and the new uib tags in the relevant html mark-up

This mostly fixes #319

### CODE REVIEW

**Comment by grtjn** [comment]
Looks great at first glance, thanks!

**Comment by grtjn** [comment]
Nish, would it be possible to rebase this? I think you will find you can drop the `@link-color` change..

**Comment by grtjn** [comment]
After rebase by Nish, anyone up for testing this? Just generate a vanilla app with this, and check if:

- pagination works/looks good
- snippet dropdown works/looks good
- same for tabs on details page
- and also login mode `modal`

**Comment by ryanjdew** [comment]
@grtjn I can test.

**Comment by grtjn** [comment]
@ryan321: you also wanted to help out. Would you like to take this, or can @ryanjdew have it? :)

**Comment by ryanjdew** [comment]
I've tested the following and everything worked properly.

- pagination works/looks good
- snippet dropdown works/looks good
- same for tabs on details page
- and also login mode `modal`

**Comment by Audarth** [comment]
Okay, I just pushed my rebased version but I tested on my local and it seemed to work fine.

**Comment by grtjn** [comment]
I was wondering about typeahead, if that works or not as is. In worst case it won't work without the ml-search change, but this PR doesn't have to wait for that any longer..

**Pull request merged**
