### PR TITLE
Fixes #64 - App secret

### LINKED ISSUE #64: Generate new (random) secret key for expressSession
Every app that is generated, starts with expressSession secret key '1234567890QWERTY'. Generate a real random one, or at least make it more unique (by prepending app-name, timestamp or whatever).

### PR DESCRIPTION
**Pull request by hunterwilliams**
Generates a better app secret by using uuid and also now replaces instances of `@sample-app` with `answers.nameDashed` #64

### CODE REVIEW

**Comment by grtjn** [comment]
Looks very promising, will test today!

**Comment by grtjn** [comment]
Works like a charm!

Can you make a few extra changes?

- `(app/templates/)bower.json` lists name `ml-node-seed`. Can you replace it there as well?
- `(app/templates/)ui/index.html` has an empty `<title>`. Can you insert the app name there too?

Not really related, but would you mind also fixing this while you are at it?

- `(app/templates/)[bower | package | mlpm].json` list different versions. Can you synch them?
- Can you add `private: true` to all three as well?

**Comment by hunterwilliams** [comment]
Would Index.html get appNameDashed or regular app name? Super easy to do either. 

Will knock them all out this weekend or Monday

**Comment by grtjn** [comment]
I had to lookup the diff, but it is just a title, so doesn't really matter too much. I'd be fine either way. It is just to make it a little easier find the right tab back, when you have many open.. :)

**Comment by hunterwilliams** [comment]
All changes should be present

**Pull request merged**
