### PR TITLE
CreateController - Fixed lint error and made tag test work properly

### PR DESCRIPTION
**Pull request by hunterwilliams**
Saw issues during gulp test. Fixed now. Project could use a Jenkins CI or something #144

### CODE REVIEW

**Comment by grtjn** [comment]
Thnx for catching this! I actually copied that delete from demo-cat, doesn't that work? Not very important, looks good like this!

**Comment by hunterwilliams** [comment]
Delete just seemed weird for accessing the value for the textbox. Since the variable would be gone right? At least normally without angular. 

So I just returned it to its start state.

**Comment by grtjn** [comment]
Angular can be very forgiving.. :P

**Comment by grtjn** [comment]
Worked for me. I'll be using `gulp autotest` from now on!

**Pull request merged**
