### PR TITLE
#69 - Added ESRI Maps Integration

### PR DESCRIPTION
**Pull request by daveegrant**
Added ability to optionally install ESRI Maps integration.

### CODE REVIEW

**Comment by dmcassel** [comment]
I haven't had a chance to review this and probably won't for a couple weeks. Anybody else up for it?

**Comment by grtjn** [comment]
@daveegrant could you append a commit to switch around detail.html and detail-no-esri.html. Make it detail.html (the default), and detail-esri.html. Maybe also comment the script tags for esri to save a bit on load time..

Otherwise I'd say, accept if it doesn't break anything. I will try to take a look on short notice..

**Comment by grtjn** [comment]
I was rethinking my comment above. It would be supercool if it were possible to isolate esri stuff more as a plugin, or maybe some module that could be installed at will instead of just at initialization. Not sure slush could cater installing extra modules in a later stage, and not sure slush is the most appropriate tool for this either. Making a bower component out of it might make sense as well..

Having said that, doing it like this works good enough for now I guess.

And regarding my remark of making non-esri default: I didn't realize that it was done such that slush will by default remove esri stuff. It might have been nicer if it was done the other way around, but I guess inserting lines is more difficult than getting rid of them.

I'll have a quick run later this weekend to see if it runs, and merge the PR if it does..

**Comment by grtjn** [comment]
Tested both with and without esri. Apart from the jsonEplorer issue, all worked well..

**Pull request merged**
