### PR TITLE
No Cache Requests

### PR DESCRIPTION
**Pull request by hunterwilliams**
A bug with edge browser/IE based browsers caching requests - see #110 

Not sure this is the perfect solution but I didn't want to try and force all requests to be no-cache

### CODE REVIEW

**Comment by grtjn** [comment]
Maybe put that in a helper function, and then add a few more headers to be paranoid:

http://stackoverflow.com/a/4485194/918496

;-)

**Comment by hunterwilliams** [comment]
I could sorta toss into a helper function however not sure about adding all of those headers.. Not sure if it affects anything though

**Comment by grtjn** [comment]
Not sure how important they are. Perhaps just for legacy browsers? Then again, not a big deal either. It won't break anything.. :P

**Comment by grtjn** [comment]
How about adding the helper function, and add those other headers as commented lines with a comment above them reading something like: For legacy browsers

**Comment by hunterwilliams** [comment]
Done. May want to move into another file it if gets any more complicated

**Comment by grtjn** [comment]
Hmm, I added a proxy rule for DELETE in PR #177 (see also #176). Think I should rebase that PR after this gets merged..

**Comment by grtjn** [comment]
@hunterwilliams I think we can drop the noCache for /v1 GET (proxy.js). Otherwise runs fine on my end..

**Comment by grtjn** [comment]
On second thought, maybe we should drop the noCache for MarkLogic entirely (e.g. don't apply to proxy.js). MarkLogic should be returning such headers itself, and my #177 PR makes sure those headers are forwarded..

**Comment by grtjn** [comment]
On third thought, not really sure MarkLogic does properly.. :-/

**Comment by hunterwilliams** [comment]
Unfortunately MarkLogic doesn't send the headers so your searches get cached...

**Comment by grtjn** [comment]
Yes, indeed. Do we want GET calls to MarkLogic get cached or not? Most searches use POST I think. Maybe a noCache for GET does sound right after all?

**Comment by hunterwilliams** [comment]
I'd assume we don't want anything to MarkLogic cached. Someone will eventually add some GET endpoint and then be hosed on IE and can't figure out why GET requests seem to fail

**Comment by grtjn** [comment]
ok, no further changes required then..

**Pull request merged**
