### PR TITLE
Fixed #148: stub mlpm.json to make mlpm install slightly easier

### LINKED ISSUE #148: Provide a bare mlpm.json to make mlpm install for deps easier
Could be pretty dumb one, not intended for mlpm publish. (can we prevent accidental mlpm publish?)

### PR DESCRIPTION
**Pull request by grtjn**
#148

### CODE REVIEW

**Comment by joemfb** [comment]
I'd recommend removing the repository field. It's not required, and trivially added to an existing project by re-running `mlpm init`.

**Comment by grtjn** [comment]
empty string or get rid of property?

**Comment by joemfb** [comment]
Just delete the property.

**Comment by grtjn** [comment]
Done, moved mlpm.json to the right place as well.

Did a rebase as well (I had to), but now I am seeing a commit from Marianne here??

**Comment by grtjn** [comment]
Redid the entire branch, now clean. Good to go?

**Comment by joemfb** [comment]
Looks good to me.

**Pull request merged**
