### PR TITLE
Fixed #193: show result.label if exists

### LINKED ISSUE #193: Show label instead of uri for results
Spin-off from PR #130, and pretty much implemented in ml-search-ng: https://github.com/joemfb/ml-search-ng/issues/76

Only requires bower update on next ml-search-ng release. Default behavior of ml-search-ng will already show 'filename' instead of full uri by default.

### PR DESCRIPTION
**Pull request by grtjn**
Get ahead of ml-search-ng release for label support. #193

### CODE REVIEW

**Comment by grtjn** [comment]
Heh fun, created this PR directly from Github site.. :)

**Comment by grtjn** [comment]
Harmless change, merging..

**Comment by joemfb** [comment]
Looks like this'll need a patch; you have binary OR `|` instead of logical OR `||`.

**Comment by grtjn** [comment]
Auch, fixing that now..

**Pull request merged**
